name: Commit CI

on:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+.*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
      - name: Install clang-format
        uses: myci-actions/add-deb-repo@11
        with:
          repo: 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main'
          repo-name: llvm
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
          install: clang-format-17
      - name: Lint
        run: |
          find src -name '*.cc' -o -name '*.h' | xargs clang-format-17 -Werror --dry-run || { echo Please lint your code by '"'"find src -name '*.cc' -o -name '*.h' | xargs clang-format -i"'"'.; false; }

  linux:
    needs: lint
    uses: ./.github/workflows/linux-build.yml

  macos:
    needs: lint
    uses: ./.github/workflows/macos-build.yml

  windows:
    needs: lint
    uses: ./.github/workflows/windows-build.yml

  docker:
    needs: lint
    uses: ./.github/workflows/docker-build.yml
